### ISSUE TITLE
Settings Page UI

### ISSUE THREAD

**Issue by shriakhilc** [Nischay-Pro/manga-notifier#1]
- [x] While typing the first url, it goes off screen to the left despite having ample space in the right. Might have something to do with the width of the field in CSS/HTML.
- [x] Find a better way to display a large number of URLs. Maybe shorten the URL to page name for display.

**Comment by shriakhilc** [comment]
- [x] Add a debug mode option to the settings. Disable logs when not in this mode.

**Comment by Nischay-Pro** [comment]
It's tough to extract the title from URL since cross-site scripting is prevented and we can't extract and get meaningful data from the URL itself for the title.
