### ISSUE TITLE
Domain changes

### ISSUE THREAD

**Issue by shriakhilc** [Nischay-Pro/manga-notifier#10]
Mangafox changed it's domain from mangafox.me/ to mangafox.la/ . Requests to the old domain are still working and thus the extension shouldn't be affected. But since that isn't guaranteed to keep working, the URLs within the extension should be modified accordingly.

**Comment by shriakhilc** [comment]
While we're at it, mangastream.com/ changed to readms.net/ earlier, but no changes were made since it was redirecting the old links to the new ones. Change those too.

**Comment by Nischay-Pro** [comment]
Commit 5270487 fixed the issue
