### ISSUE TITLE
Add URL from current tab

### ISSUE THREAD

**Issue by shriakhilc** [Nischay-Pro/manga-notifier#5]
Provide an additional browser action that lets users add the currently active tab's url to the list of urls in the settings. (So there needs to be another option above "settings" that says "Add URL". A suitable icon should be added as well)

The way to go about it would be to use the `tabs` API ( specifically `activeTab`) and getting the url of the current tab. Then use `browser.storage.local.get` to read the current list of urls, append the current url to the list and then `browser.storage.local.set` to complete the addition.

**Comment by jeffsieu** [comment]
I can work on this.

**Comment by shriakhilc** [comment]
Sure. Please follow the usual conventions for good commit messages, like the ones listed [here](https://chris.beams.io/posts/git-commit/).

**Comment by jeffsieu** [comment]
Hi, please take a look at the pull request I have made here: https://github.com/Nischay-Pro/manga-notifier/pull/6

**Comment by shriakhilc** [comment]
Fixed in PR #6
